# Generated by Django 4.0.4 on 2022-04-19 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pyzza',
            new_name='Pizza',
        ),
    ]
