# Generated by Django 4.0.4 on 2022-04-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_rename_pyzza_pizza'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='nombre',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
